window.esdocSearchIndex = [
  [
    "narou~index",
    "class/src/index.js~Index.html",
    "<span>Index</span> <span class=\"search-result-import-path\">narou</span>",
    "class"
  ],
  [
    "narou/lib/search-builder.js~searchbuilder",
    "class/src/search-builder.js~SearchBuilder.html",
    "<span>SearchBuilder</span> <span class=\"search-result-import-path\">narou/lib/search-builder.js</span>",
    "class"
  ],
  [
    "narou/lib/search-builder-r18.js~searchbuilderr18",
    "class/src/search-builder-r18.js~SearchBuilderR18.html",
    "<span>SearchBuilderR18</span> <span class=\"search-result-import-path\">narou/lib/search-builder-r18.js</span>",
    "class"
  ],
  [
    "narou/lib/narou-search-results.js~narousearchresults",
    "class/src/narou-search-results.js~narousearchresults.html",
    "<span>narousearchresults</span> <span class=\"search-result-import-path\">narou/lib/narou-search-results.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "",
    "test-file/test/narou-test.js.html#lineNumber8",
    "narou-test",
    "test"
  ],
  [
    "",
    "test-file/test/narou-test.js.html#lineNumber9",
    "narou-test search",
    "test"
  ],
  [
    "",
    "test-file/test/narou-test.js.html#lineNumber68",
    "narou-test search gzip support",
    "test"
  ],
  [
    "",
    "test-file/test/narou-test.js.html#lineNumber10",
    "narou-test search if limit = 1 then length = 1",
    "test"
  ],
  [
    "",
    "test-file/test/narou-test.js.html#lineNumber44",
    "narou-test search ncode N1707CX is テスト小説なのです。",
    "test"
  ],
  [
    "",
    "test-file/test/narou-test.js.html#lineNumber20",
    "narou-test search ncode n1701bm is 異世界食堂",
    "test"
  ],
  [
    "",
    "test-file/test/narou-test.js.html#lineNumber31",
    "narou-test search ncode n1701bm, n1443bp is 異世界食堂. 異世界はスマートフォンとともに。",
    "test"
  ],
  [
    "",
    "test-file/test/narou-test.js.html#lineNumber56",
    "narou-test search word テスト小説なのです。",
    "test"
  ],
  [
    "src/fields.js",
    "file/src/fields.js.html",
    "src/fields.js",
    "file"
  ],
  [
    "src/fields.js~fields",
    "typedef/index.html#static-typedef-Fields",
    "src/fields.js~Fields",
    "typedef"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~index.fields",
    "class/src/index.js~Index.html#static-get-fields",
    "src/index.js~Index.fields",
    "member"
  ],
  [
    "src/index.js~index.search",
    "class/src/index.js~Index.html#static-method-search",
    "src/index.js~Index.search",
    "method"
  ],
  [
    "src/index.js~index.searchr18",
    "class/src/index.js~Index.html#static-method-searchR18",
    "src/index.js~Index.searchR18",
    "method"
  ],
  [
    "src/narou-search-results.js",
    "file/src/narou-search-results.js.html",
    "src/narou-search-results.js",
    "file"
  ],
  [
    "src/narou-search-results.js~narousearchresult",
    "typedef/index.html#static-typedef-NarouSearchResult",
    "src/narou-search-results.js~NarouSearchResult",
    "typedef"
  ],
  [
    "src/narou-search-results.js~narousearchresults#allcount",
    "class/src/narou-search-results.js~narousearchresults.html#instance-member-allcount",
    "src/narou-search-results.js~narousearchresults#allcount",
    "member"
  ],
  [
    "src/narou-search-results.js~narousearchresults#length",
    "class/src/narou-search-results.js~narousearchresults.html#instance-member-length",
    "src/narou-search-results.js~narousearchresults#length",
    "member"
  ],
  [
    "src/narou-search-results.js~narousearchresults#limit",
    "class/src/narou-search-results.js~narousearchresults.html#instance-member-limit",
    "src/narou-search-results.js~narousearchresults#limit",
    "member"
  ],
  [
    "src/narou-search-results.js~narousearchresults#page",
    "class/src/narou-search-results.js~narousearchresults.html#instance-member-page",
    "src/narou-search-results.js~narousearchresults#page",
    "member"
  ],
  [
    "src/narou-search-results.js~narousearchresults#start",
    "class/src/narou-search-results.js~narousearchresults.html#instance-member-start",
    "src/narou-search-results.js~narousearchresults#start",
    "member"
  ],
  [
    "src/narou-search-results.js~narousearchresults#values",
    "class/src/narou-search-results.js~narousearchresults.html#instance-member-values",
    "src/narou-search-results.js~narousearchresults#values",
    "member"
  ],
  [
    "src/narou.js",
    "file/src/narou.js.html",
    "src/narou.js",
    "file"
  ],
  [
    "src/search-builder-r18.js",
    "file/src/search-builder-r18.js.html",
    "src/search-builder-r18.js",
    "file"
  ],
  [
    "src/search-builder-r18.js~searchbuilderr18#execute",
    "class/src/search-builder-r18.js~SearchBuilderR18.html#instance-method-execute",
    "src/search-builder-r18.js~SearchBuilderR18#execute",
    "method"
  ],
  [
    "src/search-builder.js",
    "file/src/search-builder.js.html",
    "src/search-builder.js",
    "file"
  ],
  [
    "src/search-builder.js~searchbuilder#buntai",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-buntai",
    "src/search-builder.js~SearchBuilder#buntai",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#execute",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-execute",
    "src/search-builder.js~SearchBuilder#execute",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#fields",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-fields",
    "src/search-builder.js~SearchBuilder#fields",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#gzip",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-gzip",
    "src/search-builder.js~SearchBuilder#gzip",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#isbl",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-isBL",
    "src/search-builder.js~SearchBuilder#isBL",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#isgl",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-isGL",
    "src/search-builder.js~SearchBuilder#isGL",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#ispickup",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-isPickup",
    "src/search-builder.js~SearchBuilder#isPickup",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#isr15",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-isR15",
    "src/search-builder.js~SearchBuilder#isR15",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#isstop",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-isStop",
    "src/search-builder.js~SearchBuilder#isStop",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#iszankoku",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-isZankoku",
    "src/search-builder.js~SearchBuilder#isZankoku",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#kaiwaritu",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-kaiwaritu",
    "src/search-builder.js~SearchBuilder#kaiwaritu",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#lastupdate",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-lastUpdate",
    "src/search-builder.js~SearchBuilder#lastUpdate",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#length",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-length",
    "src/search-builder.js~SearchBuilder#length",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#limit",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-limit",
    "src/search-builder.js~SearchBuilder#limit",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#ncode",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-ncode",
    "src/search-builder.js~SearchBuilder#ncode",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#notword",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-notWord",
    "src/search-builder.js~SearchBuilder#notWord",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#order",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-order",
    "src/search-builder.js~SearchBuilder#order",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#page",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-page",
    "src/search-builder.js~SearchBuilder#page",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#params",
    "class/src/search-builder.js~SearchBuilder.html#instance-member-params",
    "src/search-builder.js~SearchBuilder#params",
    "member"
  ],
  [
    "src/search-builder.js~searchbuilder#sasie",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-sasie",
    "src/search-builder.js~SearchBuilder#sasie",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#start",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-start",
    "src/search-builder.js~SearchBuilder#start",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#time",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-time",
    "src/search-builder.js~SearchBuilder#time",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#type",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-type",
    "src/search-builder.js~SearchBuilder#type",
    "method"
  ],
  [
    "src/search-builder.js~searchbuilder#word",
    "class/src/search-builder.js~SearchBuilder.html#instance-method-word",
    "src/search-builder.js~SearchBuilder#word",
    "method"
  ],
  [
    "test/narou-test.js",
    "test-file/test/narou-test.js.html",
    "test/narou-test.js",
    "testFile"
  ]
]